### ISSUE TITLE
Common ngrams 

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#17]
**Objective**
Identify common ngrams in the text

**Description**
 An n-gram is simply any sequence of n tokens (words/characters). Not only is it interesting to find common n-grams (uni, bi, tri) in the dataset, but also it can improve our modeling. 

**Skills**
basic data science/programming

**Tools**
ngram functions in the repo

**Time Estimation**
NA

**Detailed description/notes**

**Comment by mgeyrdnlr** [comment]
Hey, I'd like to self-assign this task, but doesn't work.
