### ISSUE TITLE
Store datasets in the cloud 

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#26]
**Objective**
Store our dataset in cloud storage so that they are protected, but we can allow people access for hackathons or sprints or new joiners.

**Description**
We current have these datasets:

hatespeech - obtained from Zeerak Waseem. 
aws_annotated - our annotations + hatespeech
stanford_hatespeech - stanford (aws_annotated+snorkel labels) + hatespeech
gold - stanford_hatespeech + AMI
metoo - tweet ids from https://github.com/datacamp/datacamp-metoo-analysis
rapeglish - scraped from random rape threat generator by Emma Jane
dataturks - obtained from dataturks crowdsource labeling

Most of these are able to be shared, the only one which is not is the **gold** dataset. What we would like is to be able to grant people access to all the datasets except **gold** and have a different access to that one.

**Skills**
Cloud computing eg, S3 buckets on AWS

**Tools**
You will need our accounts. Currently we have an amazon account but it is not new. We could potential chase cheap/free plans with google as we have a contact there, but this will be subject to them agreeing to it.

**Time Estimation**
NA - needs further discussion

**Detailed description/notes**
- The combined datasets are no larger than 10GB.
- We have an AWS account but nothing else
- We would  also like to store our huge collection of tweets somewhere (10GB dataset at least), but this is to do later

**Comment by muaazsaleem** [comment]
Given the size of the datasets, I think storage should be pretty cheap (I could get back with exact-ish numbers) so AWS S3 should be a good first option.

We can manage access using [AWS IAM roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html). It has all the bells and whistles we could need. We can always switch to other AWS storage services transparently (e.g [Glacier](https://aws.amazon.com/glacier/)) if we want.

**Comment by malteserteresa** [comment]
We should be getting some GCP credits so we shall move forward with google. Once we have those credits we can think about cloud storage but until then googledrive will do.
