### ISSUE TITLE
Source original Tweet from response

### ISSUE THREAD

**Issue by MikeJohnPage** [opt-out-tools/study-online-misogyny#40]
If a Tweet is a reply, can the original Tweet be sourced?

**Comment by MikeJohnPage** [comment]
In relation to the {rtweet} R package, the `search_tweet` function returns a `reply_to_status_id` variable containing the integer representation of the original Tweet’s ID (see the original [Twitter API Docs](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object) for more info). This ID can then be piped into the `lookup_tweets` function which I believe returns the Tweet the response was addressing. If this is not the the top-level Tweet of the thread, I guess this process could just be iterated over until the whole thread has been retrieved.

**Comment by MikeJohnPage** [comment]
In relation to the {rtweet} R package, the `search_tweet` function returns a `reply_to_status_id` variable containing the integer representation of the original Tweet’s ID (see the original [Twitter API Docs](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object) for more info). This ID can then be piped into the `lookup_tweets` function which I believe returns the Tweet the response was addressing. If this is not the the top-level Tweet of the thread, I guess this process could just be iterated over until the whole thread has been retrieved.

**Comment by cmcaine** [comment]
Yes. just take the setdiff(reply_ids, ids), get all of those and repeat. There might be a better API for it, but no point looking unless this is a pain.

**Comment by cmcaine** [comment]
Also worth noting that there are lots of other graphs that may be useful that aren't the replies graph. These might require different scraping approaches. The best thing might be to take our own tweet samples in a way we control and that is a bit more representative.

Graphs that might be interesting:

- reply-to digraph 
- quote-tweet digraph
- user-user interaction weighted digraph
- follow digraph
- mention digraph

**Comment by cmcaine** [comment]
I also note that this person wrote 13 thousand of the tweets in the "Me too" dataset. https://twitter.com/MariaLu01256703

The next most frequent tweeter has only 605 tweets in the dataset. Histogram of the natural log of tweet frequencies:

```
julia> UnicodePlots.histogram(collect(log.(skipmissing(values(countmap(userids))))))
                ┌                                        ┐
   [ 0.0,  0.5) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 76761
   [ 0.5,  1.0) ┤▇▇▇▇▇▇▇▇ 19259
   [ 1.0,  1.5) ┤▇▇▇ 6311
   [ 1.5,  2.0) ┤▇ 1680
   [ 2.0,  2.5) ┤ 607
   [ 2.5,  3.0) ┤ 260
   [ 3.0,  3.5) ┤ 115
   [ 3.5,  4.0) ┤ 38
   [ 4.0,  4.5) ┤ 19
   [ 4.5,  5.0) ┤ 7
   [ 5.0,  5.5) ┤ 3
   [ 5.5,  6.0) ┤ 0
   [ 6.0,  6.5) ┤ 1
   [ 6.5,  7.0) ┤ 0
   [ 7.0,  7.5) ┤ 0
   [ 7.5,  8.0) ┤ 0
   [ 8.0,  8.5) ┤ 0
   [ 8.5,  9.0) ┤ 0
   [ 9.0,  9.5) ┤ 1
```
