### ISSUE TITLE
Build new dataset for misogyny against black female politicians

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#51]
**Objective**

**Description**

**Skills**

**Tools**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by eyelesbarrow** [comment]
is somebody doing this? I'm thinking of doing this if, at 1st level, entails scraping for misogynistic tweets about black female politicians to build the dataset

**Comment by malteserteresa** [comment]
I don't think so... go for it! Let me know if there's anything I can do to
help. I can help you build a twitter bit if you'd like.

**Comment by eyelesbarrow** [comment]
cool, i'll start on this wkend and if i run into problems with the twitter bit, i'll let you know

**Comment by teoguso** [comment]
Closing this and transferring to https://github.com/opt-out-tools/model-online-misogyny/projects/4#card-38336647. Maybe open a PR when you have something going or create an issue for more specific problems. :-)
