### ISSUE TITLE
Store Models in repo with VCS

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#54]
**Objective**
To have a VCS for different models.

**Description**
We will use DVC to do this. DVC does not only version models but allows one to re-run an experiment. For this functionality we are dependent on #48 

**Skills**
ML, Data engineer

**Tools**
DVC

**Time Estimation**

**Tasks**

- [ ] Get model VCS working

**Comment by teoguso** [comment]
Taking care of this in PR #73
