### ISSUE TITLE
[WIP] Investigate how to make this repo compatible with R and Python

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#68]
**Objective**

**Description**

**Skills**

**Dependencies**

**Time Estimation**

**Tasks**

- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

**Comment by teoguso** [comment]
This seems like a very hard if not impossible task. I would advise against mixing languages in the same repo (i.e. this issue should be closed).
