### ISSUE TITLE
[WIP] Improve repo usage documentation

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/study-online-misogyny#70]
**Objective**
Make the repository easy to contribute to

**Description**

**Skills**

**Dependencies**

**Time Estimation**

**Tasks**

- [ ] Establish how to share datasets dependes on issue #69
- [ ] Write instructions
- [ ] Improve description of folders in repo

**Comment by lucie-docs** [comment]
Feel free to assign this to me @malteserteresa

**Comment by andra-pumnea** [comment]
Hey @lucie-docs I just saw you were working on this. I added a step-by-step workflow in [CONTRIBUTING.md ](https://github.com/opt-out-tools/study-online-misogyny/blob/feature/%2370-improve_docs/CONTRIBUTING.md) for contributing code. I also created a new branch for documentation called feature/#70-improve_docs.

**Comment by lucie-docs** [comment]
> Hey @lucie-docs I just saw you were working on this. I added a step-by-step workflow in [CONTRIBUTING.md ](https://github.com/opt-out-tools/study-online-misogyny/blob/feature/%2370-improve_docs/CONTRIBUTING.md) for contributing code. I also created a new branch for documentation called feature/#70-improve_docs.

Thanks for letting me know @andra-pumnea !
